version: '3'

services:
  redis:
    image: redis:alpine
    expose:
      - "6379"

  web-frontend:
    image: jasonthc/appcestry-frontend:0.0.1b
    env_file:
      - ./appcestry_cluster.env
    depends_on:
      - http-interface
    ports:
      - "80:80"
    expose:
      - "80"

  http-interface:
    image: jasonthc/appcestry:0.0.1b
    env_file:
      - ./appcestry_cluster.env
    depends_on:
      - redis
    expose:
      - "8899"
    entrypoint: /appcestry/app.py

  rq-worker-convert:
    image: jasonthc/appcestry:0.0.1b
    env_file:
      - ./appcestry_cluster.env
    depends_on:
      - http-interface
      - dask-scheduler
    entrypoint: /appcestry/rq_worker_convert.sh

  rq-worker-compare:
    image: jasonthc/appcestry:0.0.1b
    env_file:
      - ./appcestry_cluster.env
    depends_on:
      - http-interface
      - dask-scheduler
    entrypoint: /appcestry/rq_worker_compare.sh

  dask-scheduler:
    image: jasonthc/appcestry:0.0.1b
    env_file:
      - ./appcestry_cluster.env
    expose:
      - "8786"
    command: /appcestry/dask_scheduler.sh

  dask-worker:
    image: jasonthc/appcestry:0.0.1b
    env_file:
      - ./appcestry_cluster.env
    depends_on:
      - dask-scheduler
    command: /appcestry/dask_worker.sh
